using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace QuickerExpressionAgent.Server.Embed;

/// <summary>
/// Source generator to generate EmbeddedConfig from .env file at compile time
/// </summary>
[Generator]
public class EmbeddedConfigGenerator : ISourceGenerator
{
	public void Initialize(GeneratorInitializationContext context)
	{
		// No initialization needed
	}

	public void Execute(GeneratorExecutionContext context)
	{
		try
		{
			// Find .env file in AdditionalFiles
			string? envContent = null;
			string? envFilePath = null;
			foreach (var additionalFile in context.AdditionalFiles)
			{
				var fileName = Path.GetFileName(additionalFile.Path);
				if (fileName.Equals(".env", StringComparison.OrdinalIgnoreCase))
				{
					envContent = additionalFile.GetText()?.ToString();
					envFilePath = additionalFile.Path;
					break;
				}
			}

			// Report error if .env file doesn't exist
			if (string.IsNullOrEmpty(envContent))
			{
				var descriptor = new DiagnosticDescriptor(
					"EMBED002",
					".env file not found",
					".env file is required but not found. Please create a .env file in the project directory with DEEPSEEK_API_KEY and/or GLM_API_KEY. BaseUrl and ModelId are hardcoded in ConfigurationService.",
					"EmbeddedConfig",
					DiagnosticSeverity.Error,
					isEnabledByDefault: true);
				
				context.ReportDiagnostic(Diagnostic.Create(descriptor, Location.None));
				return;
			}

			// Read .env file - only read API keys
			string deepseekApiKey = "";
			string glmApiKey = "";

			var lines = envContent.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries);

			foreach (var line in lines)
			{
				// Skip comments and empty lines
				var trimmedLine = line.Trim();
				if (string.IsNullOrEmpty(trimmedLine) || trimmedLine.StartsWith("#"))
					continue;

				// Parse KEY=VALUE format
				var match = Regex.Match(trimmedLine, @"^([^=]+)=(.*)$");
				if (match.Success)
				{
					var key = match.Groups[1].Value.Trim();
					var value = match.Groups[2].Value.Trim();

					// Remove quotes if present
					if ((value.StartsWith("\"") && value.EndsWith("\"")) ||
					    (value.StartsWith("'") && value.EndsWith("'")))
					{
						value = value.Substring(1, value.Length - 2);
					}

					var upperKey = key.ToUpperInvariant();
					switch (upperKey)
					{
						// DeepSeek API Key (for backward compatibility, also support OPENAI_API_KEY)
						case "DEEPSEEK_API_KEY":
						case "OPENAI_API_KEY":
						case "OPENAI:APIKEY":
							deepseekApiKey = value;
							break;
						// GLM API Key
						case "GLM_API_KEY":
						case "ZHIPU_API_KEY":
							glmApiKey = value;
							break;
					}
				}
			}

			// Generate C# code - only API keys
			var source = GenerateSourceCode(deepseekApiKey, glmApiKey);
			context.AddSource("EmbeddedConfig.generated.cs", SourceText.From(source, Encoding.UTF8));
		}
		catch (Exception ex)
		{
			// Report diagnostic error
			var descriptor = new DiagnosticDescriptor(
				"EMBED001",
				"Failed to generate EmbeddedConfig",
				"Failed to generate EmbeddedConfig: {0}",
				"EmbeddedConfig",
				DiagnosticSeverity.Error,
				isEnabledByDefault: true);
			
			context.ReportDiagnostic(Diagnostic.Create(descriptor, Location.None, ex.Message));
		}
	}



	private string GenerateSourceCode(string deepseekApiKey, string glmApiKey)
	{
		// Escape strings for C# string literals
		deepseekApiKey = EscapeString(deepseekApiKey);
		glmApiKey = EscapeString(glmApiKey);

		return $@"// <auto-generated />
// This file is generated at compile time from .env
// DO NOT EDIT THIS FILE MANUALLY

namespace QuickerExpressionAgent.Server.Generated;

/// <summary>
/// Embedded configuration generated at compile time
/// Only manages API keys. BaseUrl and ModelId are hardcoded in ConfigurationService.
/// </summary>
internal static partial class EmbeddedConfig
{{
    /// <summary>
    /// DeepSeek API Key (also supports OPENAI_API_KEY for backward compatibility)
    /// </summary>
    internal static readonly string DeepSeekApiKey = {deepseekApiKey};
    
    /// <summary>
    /// GLM (Zhipu) API Key
    /// </summary>
    internal static readonly string GlmApiKey = {glmApiKey};
    
    /// <summary>
    /// Default API Key (for backward compatibility, uses DeepSeek API Key)
    /// </summary>
    internal static readonly string ApiKey = DeepSeekApiKey;
}}
";
	}

	private static string EscapeString(string value)
	{
		if (string.IsNullOrEmpty(value))
			return "\"\"";

		// Escape special characters for C# string literal
		var escaped = value
			.Replace("\\", "\\\\")
			.Replace("\"", "\\\"")
			.Replace("\n", "\\n")
			.Replace("\r", "\\r")
			.Replace("\t", "\\t");

		return $"\"{escaped}\"";
	}
}

