# BuildTools 简化配置文件
# 将此文件放在你的项目根目录，然后运行 BuildTools.exe 即可自动构建

# 基本项目信息
name: wpf-2048
displayName: Wpf2048
versionKey: Wpf2048          # 对应 version.json 中的键名
subprogramName: Wpf2048
# 项目路径（可选，默认为当前目录）
projectDir: src/Wpf2048

# 发布相关配置
uploadDir: cea.wpf-2048
packageName: cea.wpf-2048
instruction: WPF 2048 游戏

# 文件处理配置
filesToInclude:
  - "Wpf2048*.dll"
binaryFilter: "Wpf2048*"
filesToExclude:               # 要排除的文件
  - "*.pdb"
  - "*.xml"

# 混淆配置（可选）
obfuscate: true
toConfuse:                    # 要混淆的文件（当 obfuscate: true 时）
  - "Wpf2048.{version}.dll"

# 测试配置（可选）
testDir: "Quicker/_packages/cea.wpf-2048"

# 构建控制
enabled: true


