# BuildTools 简化配置文件
# 将此文件放在你的项目根目录，然后运行 BuildTools.exe 即可自动构建

# 基本项目信息
name: xml-extract-tool
displayName: XmlExtractTool
versionKey: XmlExtractTool          # 对应 version.json 中的键名
subprogramName: XmlExtractTool
# 项目路径（可选，默认为当前目录）
projectDir: src/XmlExtractTool

# 发布相关配置
uploadDir: cea.xml-extract-tool
packageName: cea.xml-extract-tool
instruction: XML Extract Tool - XML 四元数检测工具

# 文件处理配置
filesToInclude:                    # 要包含的文件（支持通配符，如果指定则只包含匹配的文件）
  - "XmlExtractTool*.dll"
filesToExclude:                    # 要排除的文件（支持通配符）
  - "*.pdb"
  - "*.xml"

# 混淆配置（可选）
obfuscate: true                    # 是否启用混淆
toConfuse:                         # 要混淆的文件列表（当 obfuscate: true 时）
  - "XmlExtractTool.{version}.dll"
