# BuildTools simplified configuration

name: webview-markdown-tip
displayName: WebViewMarkdownTip
versionKey: WebViewMarkdownTip
subprogramName: WebViewMarkdownTip
projectDir: src/WebViewMarkdownTip

uploadDir: cea.webview-markdown-tip
packageName: cea.webview-markdown-tip
instruction: WebView Markdown tip window (React + WebView2)

filesToInclude:
  - "WebViewMarkdownTip*.dll"
  - "Web/**/*"
filesToExclude:
  - "*.pdb"
  - "*.xml"

obfuscate: true
toConfuse:
  - "WebViewMarkdownTip.{version}.dll"
