# BuildTools 简化配置文件
# 将此文件放在你的项目根目录，然后运行 BuildTools.exe 即可自动构建

# 基本项目信息
name: quicker-code-editor
displayName: QuickerCodeEditor
versionKey: QuickerCodeEditor          # 对应 version.json 中的键名
subprogramName: QuickerCodeEditor
# 项目路径（可选，默认为当前目录）
projectDir: src/QuickerCodeEditor

# 发布相关配置
uploadDir: cea.quicker-code-editor
packageName: cea.quicker-code-editor
instruction: Quicker Code Editor

# 文件处理配置
filesToInclude:                    # 要包含的文件（支持通配符，如果指定则只包含匹配的文件）
  - "QuickerCodeEditor*.dll"
filesToExclude:                    # 要排除的文件（支持通配符）
  - "*.pdb"
  - "*.xml"

# 混淆配置（可选）
obfuscate: true                    # 是否启用混淆
toConfuse:                         # 要混淆的文件列表（当 obfuscate: true 时）
  - "QuickerCodeEditor.{version}.dll"

