using System;
using System.Windows;
using DependencyPropertyGenerator;
using Windows.Win32;
using Windows.Win32.Foundation;
using Windows.Win32.UI.WindowsAndMessaging;
using static Windows.Win32.PInvoke;
using WindowEdgeHide.Models;
using WindowEdgeHide.Utils;

namespace WindowEdgeHide.Services
{
    /// <summary>
    /// Managed window that monitors window state through hooks
    /// Provides dependency properties for IsVisible, IsActive, and WindowState
    /// </summary>
    [DependencyProperty<bool>("IsVisible", DefaultValue = true)]
    [DependencyProperty<bool>("IsActive", DefaultValue = false)]
    [DependencyProperty<Models.WindowState>("WindowState", DefaultValue = Models.WindowState.Normal)]
    [DependencyProperty<bool>("Topmost", DefaultValue = false)]
    public partial class ManagedWindow : DependencyObject, IDisposable
    {
        private readonly HWND _windowHandle;
        private WindowStateHook? _stateHook;

        /// <summary>
        /// Event raised when IsVisible property changes
        /// </summary>
        public event EventHandler<bool>? IsVisibleChanged;

        /// <summary>
        /// Event raised when IsActive property changes
        /// </summary>
        public event EventHandler<bool>? IsActiveChanged;

        /// <summary>
        /// Event raised when WindowState property changes
        /// </summary>
        public event EventHandler<Models.WindowState>? WindowStateChanged;

        /// <summary>
        /// Event raised when Topmost property changes
        /// </summary>
        public event EventHandler<bool>? TopmostChanged;

        /// <summary>
        /// Window handle
        /// </summary>
        public IntPtr Handle => _windowHandle.Value;

        // Dependency properties are auto-generated by DependencyPropertyGenerator
        // Use partial methods for change callbacks
        partial void OnIsVisibleChanged(bool oldValue, bool newValue)
        {
            IsVisibleChanged?.Invoke(this, newValue);
        }

        partial void OnIsActiveChanged(bool oldValue, bool newValue)
        {
            IsActiveChanged?.Invoke(this, newValue);
        }

        partial void OnWindowStateChanged(Models.WindowState oldValue, Models.WindowState newValue)
        {
            WindowStateChanged?.Invoke(this, newValue);
        }

        partial void OnTopmostChanged(bool oldValue, bool newValue)
        {
            TopmostChanged?.Invoke(this, newValue);
            // Update actual window topmost state
            WindowHelper.SetWindowTopmost(_windowHandle.Value, newValue);
        }

        /// <summary>
        /// Create a managed window instance
        /// </summary>
        /// <param name="windowHandle">Window handle to monitor</param>
        public ManagedWindow(IntPtr windowHandle)
        {
            _windowHandle = new HWND(windowHandle);
            
            if (!IsWindow(_windowHandle))
                throw new ArgumentException("Invalid window handle");

            // Initialize state
            UpdateIsVisible();
            UpdateWindowState();
            UpdateIsActive();
            UpdateTopmost();

            // Create state hook for real-time state detection (minimize, maximize, visibility, activation)
            _stateHook = new WindowStateHook(windowHandle);
            _stateHook.StateChanged += StateHook_StateChanged;
            _stateHook.VisibilityChanged += StateHook_VisibilityChanged;
            _stateHook.Activated += StateHook_Activated;
            _stateHook.Deactivated += StateHook_Deactivated;
            _stateHook.StartHook();
        }

        /// <summary>
        /// Update window visibility state
        /// </summary>
        private void UpdateIsVisible()
        {
            if (_windowHandle.Value == IntPtr.Zero || !IsWindow(_windowHandle))
                return;

            bool isVisible = Windows.Win32.PInvoke.IsWindowVisible(_windowHandle);
            if (IsVisible != isVisible)
            {
                IsVisible = isVisible;
            }
        }

        /// <summary>
        /// Update window state (Normal, Minimized, Maximized)
        /// </summary>
        private void UpdateWindowState()
        {
            if (_windowHandle.Value == IntPtr.Zero || !IsWindow(_windowHandle))
                return;

            bool isMinimized = WindowHelper.IsWindowMinimized(_windowHandle.Value);
            bool isMaximized = Windows.Win32.PInvoke.IsZoomed(_windowHandle);
            
            Models.WindowState newState;
            if (isMinimized)
                newState = Models.WindowState.Minimized;
            else if (isMaximized)
                newState = Models.WindowState.Maximized;
            else
                newState = Models.WindowState.Normal;

            if (WindowState != newState)
            {
                WindowState = newState;
            }
        }

        /// <summary>
        /// Update window activation state
        /// </summary>
        private void UpdateIsActive()
        {
            if (_windowHandle.Value == IntPtr.Zero || !IsWindow(_windowHandle))
                return;

            var foregroundWindow = WindowHelper.GetForegroundWindow();
            bool isActive = foregroundWindow == _windowHandle.Value;
            if (IsActive != isActive)
            {
                IsActive = isActive;
            }
        }

        /// <summary>
        /// Update window topmost state
        /// </summary>
        private void UpdateTopmost()
        {
            if (_windowHandle.Value == IntPtr.Zero || !IsWindow(_windowHandle))
                return;

            bool isTopmost = WindowHelper.GetWindowTopmost(_windowHandle.Value);
            if (Topmost != isTopmost)
            {
                Topmost = isTopmost;
            }
        }

        private void StateHook_StateChanged(IntPtr windowHandle)
        {
            if (windowHandle == _windowHandle.Value)
            {
                // Window state changed (minimize, maximize, restore)
                UpdateWindowState();
            }
        }

        private void StateHook_VisibilityChanged(IntPtr windowHandle, bool isVisible)
        {
            if (windowHandle == _windowHandle.Value)
            {
                // Window visibility changed
                IsVisible = isVisible;
            }
        }

        private void StateHook_Activated(IntPtr windowHandle)
        {
            if (windowHandle == _windowHandle.Value)
            {
                // Update activation state immediately
                UpdateIsActive();
            }
        }

        private void StateHook_Deactivated(IntPtr windowHandle)
        {
            if (windowHandle == _windowHandle.Value)
            {
                // Update activation state immediately
                UpdateIsActive();
            }
        }

        public void Dispose()
        {
            if (_stateHook != null)
            {
                _stateHook.StateChanged -= StateHook_StateChanged;
                _stateHook.VisibilityChanged -= StateHook_VisibilityChanged;
                _stateHook.Activated -= StateHook_Activated;
                _stateHook.Deactivated -= StateHook_Deactivated;
                _stateHook.Dispose();
                _stateHook = null;
            }
        }
    }
}

